#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

traj_num=0
traj=none

for f in "$DIR"/*; do
  fn="$(basename -- $f)"
  ext="${fn##*.}"
  extUP=`echo "$ext" | tr '[:lower:]' '[:upper:]'`

  if [[ "$extUP" == "TRAJ" ]]; then
    traj=$f
    traj_num=$((traj_num+1))
  fi
done

if [ $traj_num = 1 ]; then
  python /OpenMMS/code/openmms_traj_convert.py $traj
fi

if [ $traj_num = 0 ]; then
  echo "No TRAJ file was found in the current directory"
fi  

if [ $traj_num -gt 1 ]; then
  echo "More than one TRAJ file was found in the current directory, only a single TRAJ file should be present"
fi


echo ""
read -p "Press Enter to continue ..."