#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

max_images="500"

python /OpenMMS/code/openmms_camera_calibration.py $DIR $max_images

echo ""
read -p "Press Enter to continue ..."