#!/bin/bash

pip install colorama
pip install pyproj
pip install pillow
pip install tqdm
pip install pyautogui
pip install numpy
pip install laspy
pip install scipy
pip install matplotlib
pip install numba
pip install numdifftools
pip install opencv-python
pip install scikit-learn